# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-29 06:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entry', '0002_entry_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entry',
            old_name='user',
            new_name='writer',
        ),
    ]
